---
title: "TR2_Draft"
output: html_document
---
```{r, echo=FALSE}
library(Matrix)
source("https://drive.google.com/uc?export=download&id=10dNH3VbvxS8Z3OHjP4i9gRbtsf91VVBb")
```

# Part 1

```{r}
A = Matrix(0,14,14,sparse = TRUE)
A[2:7,1]=1
A[c(1,6,7,14),2]=1
A[c(2,4,5),3]=1
A[c(5,8:10),4]=1
A[c(4,11:13),5]=1
A[c(7,14),6]=1
A[c(6,14),7]=1
A[10,8:9]=1
A
image(A)
```



```{r}
Katz.eigen = function(A,alphas){
  result = vector()
  for (a in alphas) {
    result = c(result,max(Mod(eigen(a*A)$values)))
  }
  return(result)
}

Katz.eigen(A, 0:100/100)  # [0,0.76] converge
```

```{r}
Katz.B = function(A, alpha) {
  return(alpha^(-1)*diag(1,nrow(A)) - t(A))
}

Katz.index = function(A, alphas) {
  d = t(A) %*% rep(1,nrow(A))
  result = vector()
  for (a in alphas) {
    B = Katz.B(A, a)
    sol = c(result, jacobi(B,d, x= rep(1,14),m=100))
    p = sol$x
    p = p/max(p)
    result = c(result, p)
  }
  return(result)
}

Katz.index(A, 1:7/10)
```

```{r}
a=0.114337645
I = diag(14)
(solve(I-a*t(A))-I) %*% rep(1,14) 
```



