
> D() 

```{r}
D<-function(f,delta=.001) {
  fun=function(x){
  (f(x+delta)-f(x))/delta
  }
  return(fun)
}
f = function(x) {x*exp(-x^2)}
df = D(f)

x = seq(-1,3,length=1000)

plot(x,f(x),type='l',main="y = f(x)")
grid()
abline(0,0,col='blue')
abline(v=0,col='blue')
plot(x,df(x),type='l',main="dy/dx = f'(x)")
grid()
abline(0,0,col='blue')
abline(v=0,col='blue')
```

```{r}


```

> Test with `Deriv` package

```{r}
library(Deriv)
df = Deriv(f)

plot(x,df(x),type='l',main="dy/dx = f'(x)")
grid()
abline(0,0,col='blue')
abline(v=0,col='blue')
```

> Newton

```{r}

Newton = function(f, x_0, num.its = 40,tol=0.5*10^-10) {
  history = rep(NA, num.its + 1)
  history[1] = x_0
  i = 0
  fprime = D(f)
  while (i < num.its ) {
    i = i + 1
    x_0 = x_0 - f(x_0)/fprime(x_0)
    history[i+1] = x_0
    
    if (abs(history[i + 1] - history[i]) < tol){
      break
    }
  }
  root = x_0
  return(list(root=root,history=history[!is.na(history)]))
}

options(digits = 12)
f=function(x) (cos(x))^2+sin(x)-1
Newton(f,4.25)
```

> visualiztion


> Q3

```{r}
f = function(x) {exp(x)}

slopes=function(f,x){
  df=D(f,delta = 10^-(1:20))
  return(df(x))
}

options(digits = 20)
slopes=slopes(f,0)  # slope should be 1
x=c(1:15)
plot(x,slopes[1:15])
e=abs((slopes[1:15]-1))
plot(x,log(e))
min(e)


slopes=function(f,x){
  df=D(f,delta = ((1:100)*10^-9))
  return(df(x))
}

options(digits = 20)
(slopes=slopes(f,0))  # slope should be 1
x=c(1:100)
plot(x,slopes[1:100])
e=abs(slopes[1:100]-1)
plot(x,log(e))
min(e)
x=c(1:20)
e=abs(slopes[1:20]-1)
plot(x,log(e))
min(e)


```

> around $\delta=10^{-8}$ is most accurate

> Test for another function

```{r}
f = function(x) {x^2}

slopes=function(f,x){
  df=D(f,delta = ((1:100)*10^-9))
  return(df(x))
}

options(digits = 20)
(slopes=slopes(f,1))  # slope should be 2
x=c(1:100)
plot(x,slopes[1:100])
(e=abs(slopes[1:100]-2))
plot(x,log(e))
min(e)
x=c(1:20)
(e=abs(slopes[1:20]-2))
plot(x,log(e))
min(e)
```

> $8\times10^{-9}$

> Consistent

> Q4

```{r}
D2<-function(f,delta=.001) {
  fun=function(x){
  (f(x+delta)-f(x-delta))/(2*delta)
  }
  return(fun)
}

f = function(x) {x^2}

slopes=function(f,x){
  df=D2(f,delta = 10^-(1:20))
  return(df(x))
}

options(digits = 20)
(slopes=slopes(f,1))  # slope should be 2
x=c(1:16)
plot(x,slopes[1:16])
(e=abs(slopes[1:16]-2))
plot(x,log(e))
min(e)
```

> It will be most accurate around $\delta=0.1$

```{r}
f = function(x) {exp(x)}

slopes=function(f,x){
  df=D2(f,delta = 10^-(1:20))
  return(df(x))
}

options(digits = 20)
slopes=slopes(f,0)  # slope should be 1
x=c(1:15)
plot(x,slopes[1:15])
e=abs((slopes[1:15]-1))
plot(x,log(e))
min(e)
```

> not consistent since it will be most consistent aroung $\delta=10^{-5}$



```{r}
D<-function(f,delta=.001) {
  fun=function(x){
  (f(x+delta)-f(x))/delta
  }
  return(fun)
}

D2<-function(f,delta=.001) {
  fun=function(x){
  (f(x+delta)-f(x-delta))/(2*delta)
  }
  return(fun)
}


f = function(x) {exp(x)}

df1=D(f,delta = 10^-(1:20))
e1=abs(df1(0)-1)

df2=D2(f,delta = 10^-(1:20))
e2=abs(df2(0)-1)
diff=log(e1)-log(e2)

plot(1:20,diff, xlab = "10^-x", ylab = "Difference in Log(Error)", main = "Plot of differences in log(error) between two methods for e^x")


f = function(x) {x^3+2*x}
df1=D(f,delta = 10^-(1:20))
e1=abs(df1(1)-5)

df2=D2(f,delta = 10^-(1:20))
e2=abs(df2(1)-5)
diff=log(e1)-log(e2)

plot(1:20,diff, xlab = "10^-x", ylab = "Difference in Log(Error)", main = "Plot of differences in log(error) between two methods for x^3+2x")


f = function(x) {sin(x)}
df1=D(f,delta = 10^-(1:20))
e1=abs(df1(pi)+1)

df2=D2(f,delta = 10^-(1:20))
e2=abs(df2(pi)+1)
diff=log(e1)-log(e2)

plot(1:20,diff, xlab = "10^-x", ylab = "Difference in Log(Error)", main = "Plot of differences in log(error) between two methods for sin(x)")

```












