---
title: "graphs"
output: html_document
---
```{r}
D<-function(f,delta=.001) {
  fun=function(x){
  (f(x+delta)-f(x))/delta
  }
  return(fun)
}
```

```{r}
f1 = function(x) {exp(x)}
f2 = function(x) {x^3+2*x}
f3 = function(x) {sin(x)}
f4 = function(x) {x^8+2*x-1}
```


```{r}
df1=D(f1,delta = 10^(-20:-1))
e1=abs(df1(0)-1)
x=c(-20:-1)
plot(x,log(e1), ylim = c(-26,3),pch=15, col = 'blue', xlab = 'Power of delta', ylab = 'Log(error)', main = 'Plot of log(error) ~ power of delta')

df2=D(f2,delta = 10^(-20:-1))
e2=abs(df2(1)-5)
points(x,log(e2), pch=17, col = 'orange')

df4=D(f4,delta = 10^(-20:-1))
e4=abs(df4(1)-10)
points(x,log(e4), pch=19, col='red')

legend(x="bottomleft", 
      legend=c("x^8+2x-1","x^3+2x","e^x"), 
      col=c("red","orange","blue"),  
      pch=c(19,17,15,18), merge=FALSE)
```

```{r}
df1=D(f1,delta = ((1:100)*10^-9))
e1=abs(df1(0)[1:40]-1)
x=c(1:40)
plot(x,log(e1), pch=15, col = 'blue', xlab = "delta=x*10^-9", ylab = 'Log(error)',ylim = c(-23,-12), main='Zoomed-in plot of log(error) ~ power of delta')

df2=D(f2,delta = ((1:100)*10^-9))
e2=abs(df2(1)[1:40]-5)
points(1:40,log(e2), pch=17, col = 'orange')

df4=D(f4,delta = ((1:100)*10^-9))
e4=abs(df4(1)-10)[1:40]
points(x,log(e4), pch=19, col='red')

legend( x="bottomright", 
        legend=c("x^8+2x-1","x^3+2x","e^x"), 
        col=c("red","orange","blue"),  
        pch=c(19,17,15), merge=FALSE )
```


```{r}
Dforward<-function(f,delta=.001) {
  result = function(x){
  (f(x+delta)-f(x))/delta
  }
  return(result)
}

Dbackward<-function(f,delta=.001) {
  result = function(x){
  (f(x)-f(x-delta))/delta
  }
  return(result)
}

D3points <- function(f,delta=.001) {
  result = function(x){
  (f(x+delta)-f(x-delta))/(2*delta)
  }
  return(result)
}
```

```{r}
df1=Dforward(f1,delta = 10^(-20:-1))
e1=abs(df1(0)-1)

df2=Dbackward(f1,delta = 10^(-20:-1))
e2=abs(df2(0)-1)

df3=D3points(f1,delta = 10^(-20:-1))
e3=abs(df3(0)-1)


df11=Dforward(f2,delta = 10^(-20:-1))
e11=abs(df11(1)-5)

df22=Dbackward(f2,delta = 10^(-20:-1))
e22=abs(df22(1)-5)

df33=D3points(f2,delta = 10^(-20:-1))
e33=abs(df33(1)-5)

diff1=log(e1)-log(e2)
diff2=log(e2)-log(e3)
diff3=log(e3)-log(e1)

diff11=log(e11)-log(e22)
diff22=log(e22)-log(e33)
diff33=log(e33)-log(e11)

plot(-20:-1,diff1, xlab = "power of delta", ylab = "Difference in Log(Error)", main = "Differences in log(error) between forward and backward difference", pch=19, col='steelblue2', ylim = c(-5,5))
points(-20:-1,diff11, pch=19, col='red')
legend( x="bottomright", 
        legend=c("x^3+2x","e^x"), 
        col=c("red","steelblue2"),  
        pch=c(19,19), merge=FALSE )

plot(-20:-1,diff2, xlab = "power of delta", ylab = "Difference in Log(Error)", main = "Differences in log(error) between backward and centered difference", pch=19, col='steelblue2', ylim = c(-15,15))
points(-20:-1,diff22, pch=19, col='red')
legend( x="bottomright", 
        legend=c("x^3+2x","e^x"), 
        col=c("red","steelblue2"),  
        pch=c(19,19), merge=FALSE )

plot(-20:-1,diff3, xlab = "power of delta", ylab = "Difference in Log(Error)", main = "Differences in log(error) between centered and forward difference",pch=19, col='steelblue2', ylim = c(-15,15) )
points(-20:-1,diff33, pch=19, col='red')
legend( x="topleft", 
        legend=c("x^3+2x","e^x"), 
        col=c("red","steelblue2"),  
        pch=c(19,19), merge=FALSE )
```

> forward is worse than backward and centered difference.


